---
- name: Reload Systemd Daemon Configurations
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart KijaniKiosk Target Service
  ansible.builtin.service:
    name: "kijanikiosk-{{ server_role }}"
    state: restarted

- name: Restart Systemd Journal Service
  ansible.builtin.service:
    name: systemd-journald
    state: restarted

- name: Enforce Active Firewall Policies
  community.general.ufw:
    state: reloaded
