---
# Challenge B Alignment: Shared connection variables for the kijanikiosk group
ansible_user: ubuntu
ansible_ssh_private_key_file: "~/.ssh/id_rsa"
ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
